## Import
* 非精确一维搜索
* 牛顿法实现无约束最优化

In [1]:
from sympy import *     # 各种函数集
import numpy as np

#from search import Line_Searcher
from newton import opt

## Functions to Be Tested
本次程序采用 正则表达式+解析法 计算梯度和Hesse阵，因此需要注意函数的形式

In [2]:
# 三维Rosenbrock函数
def fun_Rosen_3d(x):
    return 100*((x[1]-x[0]**2)**2 + (x[2]-x[1]**2)**2) + ((1-x[0])**2 + (1-x[1])**2)

# 六维Rosenbrock函数
def fun_Rosen_6d(x):
    return 100*((x[5]-x[4]**2)**2 + (x[4]-x[3]**2)**2 + (x[3]-x[2]**2)**2 \
        + (x[2]-x[1]**2)**2 + (x[1]-x[0]**2)**2) \
        + ((1-x[4])**2 + (1-x[3])**2 + (1-x[2])**2 +(1-x[1])**2 + (1-x[0])**2)

# 添加了三角函数项的Roesnbrock函数
def fun_Rosen_sin_3d(x):
    return 100*((x[1]-x[0]**2)**2 + (x[2]-x[1]**2)**2) + ((1-x[0])**2 + (1-x[1])**2) \
        + sin(1-x[1])**2 + sin(1-x[0])**2 

## Initial Points
* 由代数知识不难推出以上函数的全局最优解为 $x_{min}=[1,1,...,1]$ ，最小值为 $0$
* 设置三种不同起始点以供测试

In [3]:
x1_3d = [0,0,0]
x2_3d = [2,2,2]
x3_3d = np.random.rand(3) # 随机取点

In [4]:
x1_6d = [0,0,0,0,0,0]
x2_6d = [2,2,2,2,2,2]
x3_6d = np.random.rand(6) # 随机取点

## Optimizers
* 采用不同的参数ρ和σ进行一维搜索

In [5]:
opter1 = opt(0.3, 0.6)
opter2 = opt(0.2, 0.9)

## Test 1
先进行简单的运行测试

In [6]:
opter1.add_fun(fun_Rosen_3d)
x_3d_min = opter1.opt_newtown(x1_3d)

print(x_3d_min)
print("min: ", fun_Rosen_3d(x_3d_min))
print("reduction: ", fun_Rosen_3d(x1_3d)-fun_Rosen_3d(x_3d_min))

触发停机条件：梯度小于阈值，运行正常
[0.999999999999985 0.999999999999969 0.999999999999936]
min:  1.55761818331053e-27
reduction:  2.00000000000000


In [7]:
opter1.add_fun(fun_Rosen_6d)
x_6d_min = opter1.opt_newtown(x1_6d)

print(x_6d_min)
print("min: ", fun_Rosen_6d(x_6d_min))
print("reduction: ", fun_Rosen_6d(x1_6d)-fun_Rosen_6d(x_6d_min))

触发停机条件：梯度小于阈值，运行正常
[0.999999999999997 0.999999999999994 0.999999999999987 0.999999999999974
 0.999999999999947 0.999999999999893]
min:  4.17906460111817e-27
reduction:  5.00000000000000


## Performance Test 2 :
* 不同初始点测试
* 测试对象：六维Rosenbrock函数，三维Rosenbrock函数（三角函数）；三个初始点
* 参数设置：$\rho =0.3, \sigma = 0.6$

In [8]:
opter1.add_fun(fun_Rosen_6d)    # 不要忘了更换目标函数

print("starting point:\n", x1_6d)
x_6d_min = opter1.opt_newtown(x1_6d)
print(x_6d_min)
print("min: ", fun_Rosen_6d(x_6d_min), '\n')

print("starting point:\n", x2_6d)
x_6d_min = opter1.opt_newtown(x2_6d)
print(x_6d_min)
print("min: ", fun_Rosen_6d(x_6d_min), '\n')

print("starting point:\n", x3_6d)
x_6d_min = opter1.opt_newtown(x3_6d)
print(x_6d_min)
print("min: ", fun_Rosen_6d(x_6d_min), '\n')

starting point:
 [0, 0, 0, 0, 0, 0]
触发停机条件：梯度小于阈值，运行正常
[0.999999999999997 0.999999999999994 0.999999999999987 0.999999999999974
 0.999999999999947 0.999999999999893]
min:  4.17906460111817e-27 

starting point:
 [2, 2, 2, 2, 2, 2]
Warning! One line search might have failed.You can loop rho and sigma and retry.
触发停机条件：梯度小于阈值，运行正常
[1.00000000000000 1.00000000000000 1.00000000000000 1.00000000000001
 1.00000000000002 1.00000000000003]
min:  5.26318135202144e-28 

starting point:
 [0.56553855 0.64434032 0.19126315 0.11169696 0.09712432 0.29662242]
Warning! One line search might have failed.You can loop rho and sigma and retry.
触发停机条件：梯度小于阈值，运行正常
[1.00000000000000 1.00000000000000 1.00000000000000 1.00000000000001
 1.00000000000002 1.00000000000004]
min:  6.33356699279320e-28 



In [9]:
opter1.add_fun(fun_Rosen_sin_3d)    # 不要忘了更换目标函数

print("starting point:\n", x1_3d)
x_3d_min = opter1.opt_newtown(x1_3d)
print(x_3d_min)
print("min: ", fun_Rosen_sin_3d(x_3d_min), '\n')

print("starting point:\n", x2_3d)
x_3d_min = opter1.opt_newtown(x2_3d)
print(x_3d_min)
print("min: ", fun_Rosen_sin_3d(x_3d_min), '\n')

print("starting point:\n", x3_3d)
x_3d_min = opter1.opt_newtown(x3_3d)
print(x_3d_min)
print("min: ", fun_Rosen_sin_3d(x_3d_min), '\n')

starting point:
 [0, 0, 0]
Warning! One line search might have failed.You can loop rho and sigma and retry.
触发停机条件：梯度小于阈值，运行正常
[1.00000000000001 1.00000000000003 1.00000000000006]
min:  2.44221475495110e-27 

starting point:
 [2, 2, 2]
Warning! One line search might have failed.You can loop rho and sigma and retry.
触发停机条件：梯度小于阈值，运行正常
[1.00000000000001 1.00000000000002 1.00000000000005]
min:  1.54468826003589e-27 

starting point:
 [0.80970821 0.81740404 0.34771797]
Warning! One line search might have failed.You can loop rho and sigma and retry.
触发停机条件：梯度小于阈值，运行正常
[1. 1. 1.]
min:  7.55408272458983e-28 



## Performance Test 3:
* 不同参数选取对运行效率和结果的影响
* 测试对象：三维Rosenbrock函数（三角函数）；初始点 $[0,0,0]$；两组不同参数
* 参数选取：
    1. $\rho =0.3, \sigma = 0.6$
    2. $\rho = 0.2, \sigma =0.9$

In [18]:
opter1.add_fun(fun_Rosen_sin_3d)

print("starting point:\n", x1_3d)
x_3d_min = opter1.opt_newtown(x1_3d)
print(x_3d_min)
print("min: ", fun_Rosen_sin_3d(x_3d_min), '\n')

starting point:
 [0, 0, 0]
Warning! One line search might have failed.You can loop rho and sigma and retry.
触发停机条件：梯度小于阈值，运行正常
[1.00000000000001 1.00000000000003 1.00000000000006]
min:  2.44221475495110e-27 



In [19]:
opter2.add_fun(fun_Rosen_sin_3d)

print("starting point:\n", x1_3d)
x_3d_min = opter2.opt_newtown(x1_3d)
print(x_3d_min)
print("min: ", fun_Rosen_sin_3d(x_3d_min), '\n')

starting point:
 [0, 0, 0]
触发停机条件：梯度小于阈值，运行正常
[1.00000000000001 1.00000000000002 1.00000000000004]
min:  1.34697999566488e-27 



## Performance Test:
自由测试，您可以用已给出数据进行测试，也可以自行构造

In [17]:
'''例：任意初始点'''
# 六维Rosenbrock函数
def fun_Rosen_6d(x):
    return 100*((x[5]-x[4]**2)**2 + (x[4]-x[3]**2)**2 + (x[3]-x[2]**2)**2 \
        + (x[2]-x[1]**2)**2 + (x[1]-x[0]**2)**2) \
        + ((1-x[4])**2 + (1-x[3])**2 + (1-x[2])**2 +(1-x[1])**2 + (1-x[0])**2)

opter = opt(0.25, 0.8)
opter.add_fun(fun_Rosen_6d)
x_6d = [-1,0,1,3,4,3.2]

x_6d_min = opter.opt_newtown(x_6d)

print(x_6d_min)
print(fun_Rosen_6d(x_6d_min))

触发停机条件：梯度小于阈值，运行正常
[0.999999999999997 0.999999999999994 0.999999999999987 0.999999999999974
 0.999999999999947 0.999999999999891]
4.57976896311552e-27
